name: Update dol-en

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Update from dol-kr Release"]
    types:
      - completed

jobs:
  update_en_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r $GITHUB_WORKSPACE/scripts/requirements.txt

      - name: Install Mega CLI
        run: |
          sudo apt update
          sudo apt install -y megatools

      - name: Get latest Chrome and ChromeDriver versions
        run: |
          cd $GITHUB_WORKSPACE/scripts
          python DoLEnScraper3.py > $GITHUB_WORKSPACE/version_info.txt
          cat $GITHUB_WORKSPACE/version_info.txt
        id: get_latest_versions

      - name: Set environment variables from versions
        run: |
          source $GITHUB_WORKSPACE/version_info.txt
          echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV
          echo "CHROME_DOWNLOAD_URL=$CHROME_DOWNLOAD_URL" >> $GITHUB_ENV
          echo "CHROMEDRIVER_DOWNLOAD_URL=$CHROMEDRIVER_DOWNLOAD_URL" >> $GITHUB_ENV

      - name: Install Chrome and ChromeDriver
        run: |
          wget -O /tmp/chrome.zip $CHROME_DOWNLOAD_URL
          unzip -o /tmp/chrome.zip -d $GITHUB_WORKSPACE/chrome
          sudo mv $GITHUB_WORKSPACE/chrome/chrome-linux64/chrome /usr/bin/google-chrome
          wget -O /tmp/chromedriver.zip $CHROMEDRIVER_DOWNLOAD_URL
          unzip -o /tmp/chromedriver.zip -d $GITHUB_WORKSPACE/chromedriver
          sudo mv $GITHUB_WORKSPACE/chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver

      - name: Get current version
        id: get_version
        run: |
          echo "CURRENT_VERSION=$(cat $GITHUB_WORKSPACE/current_version.txt | cut -d '-' -f 1)" >> $GITHUB_ENV
          echo "CURRENT_VERSION_EN=$(cat $GITHUB_WORKSPACE/current_version_En.txt)" >> $GITHUB_ENV
          echo "Current Version: ${{ env.CURRENT_VERSION }}"
          echo "Current Version En: ${{ env.CURRENT_VERSION_EN }}"

      - name: Scrape for matching version link
        id: scrape_version
        run: |
          cd $GITHUB_WORKSPACE/scripts
          download_link=$(python DoLEnScraper.py ${{ env.CURRENT_VERSION }})
          echo "download_link=$download_link" >> $GITHUB_ENV
        env:
          GITHUB_ENV: $GITHUB_ENV

      - name: Check if link was found and versions match
        if: env.download_link == '' || env.CURRENT_VERSION == env.CURRENT_VERSION_EN
        run: echo "No matching version found or versions match. Skipping download."

      - name: Download the file
        if: env.download_link != '' && env.CURRENT_VERSION != env.CURRENT_VERSION_EN
        run: |
          echo "Download Link: ${{ env.download_link }}"
          cd $GITHUB_WORKSPACE/scripts
          output_filename="downloaded_file.zip"
          python DoLEnScraper2.py "${{ env.download_link }}" "$output_filename"
          ls -al "$GITHUB_WORKSPACE/scripts"

      - name: Verify downloaded file and unzip
        if: env.download_link != '' && env.CURRENT_VERSION != env.CURRENT_VERSION_EN
        run: |
          cd "$GITHUB_WORKSPACE/scripts"
          echo "Checking if file exists: downloaded_file.zip"
          if [ ! -f "downloaded_file.zip" ]; then
            echo "Error: File not found! Files in directory:"
            ls -al
            exit 1
          fi
          unzip -o "downloaded_file.zip" -d $GITHUB_WORKSPACE/DoL/
          ls -al "$GITHUB_WORKSPACE/DoL"
          rm -f "downloaded_file.zip"

      - name: List files in DoL directory
        if: env.download_link != '' && env.CURRENT_VERSION != env.CURRENT_VERSION_EN
        run: |
          ls -al "$GITHUB_WORKSPACE/DoL"
          ls -al "$GITHUB_WORKSPACE/DoL/Degrees of Lewdity"

      - name: Move HTML file and rename
        if: env.download_link != '' && env.CURRENT_VERSION != env.CURRENT_VERSION_EN
        run: |
          cd "$GITHUB_WORKSPACE/DoL/Degrees of Lewdity"
          mv "Degrees of Lewdity ${{ env.CURRENT_VERSION }}.html" "DoLEn.html"

      - name: Move all files to DoL directory
        if: env.download_link != '' && env.CURRENT_VERSION != env.CURRENT_VERSION_EN
        run: |
          cd "$GITHUB_WORKSPACE/DoL/Degrees of Lewdity"
          for file in *; do
            if [ -e "$GITHUB_WORKSPACE/DoL/$file" ]; then
              if [ -d "$GITHUB_WORKSPACE/DoL/$file" ]; then
                rm -rf "$GITHUB_WORKSPACE/DoL/$file"
              else
                rm -f "$GITHUB_WORKSPACE/DoL/$file"
              fi
            fi
            mv "$file" "$GITHUB_WORKSPACE/DoL/"
          done

      - name: Remove empty folder
        if: env.download_link != '' && env.CURRENT_VERSION != env.CURRENT_VERSION_EN
        run: |
          rm -rf "$GITHUB_WORKSPACE/DoL/Degrees of Lewdity"

      - name: Copy img folder to retexture/vanila
        if: env.download_link != '' && env.CURRENT_VERSION != env.CURRENT_VERSION_EN
        run: |
          target_dir="$GITHUB_WORKSPACE/retexture/vanila/img"
          if [ -d "$target_dir" ]; then
            rm -rf "$target_dir"
          fi
          mkdir -p $GITHUB_WORKSPACE/retexture/vanila/
          cp -rf $GITHUB_WORKSPACE/DoL/img $GITHUB_WORKSPACE/retexture/vanila/
          ls -al $GITHUB_WORKSPACE/retexture/vanila/img

      - name: Update version file
        if: env.download_link != '' && env.CURRENT_VERSION != env.CURRENT_VERSION_EN
        run: echo ${{ env.CURRENT_VERSION }} > $GITHUB_WORKSPACE/current_version_En.txt

      - name: Clean up Chrome ChromeDriver and version_info
        if: always()
        run: |
          echo "Starting cleanup process..."

          echo "Deleting Google Chrome..."
          if [ -f /usr/bin/google-chrome ]; then
            sudo rm -f /usr/bin/google-chrome
            if [ $? -eq 0 ]; then
              echo "Google Chrome deleted successfully."
            else
              echo "Failed to delete Google Chrome."
            fi
          else
            echo "Google Chrome not found."
          fi

          echo "Deleting ChromeDriver..."
          if [ -f /usr/local/bin/chromedriver ]; then
            sudo rm -f /usr/local/bin/chromedriver
            if [ $? -eq 0 ]; then
              echo "ChromeDriver deleted successfully."
            else
              echo "Failed to delete ChromeDriver."
            fi
          else
            echo "ChromeDriver not found."
          fi

          echo "Deleting Chrome workspace directories..."
          if [ -d "$GITHUB_WORKSPACE/chrome" ]; then
            sudo chmod -R 777 "$GITHUB_WORKSPACE/chrome"
            sudo rm -rf "$GITHUB_WORKSPACE/chrome"
            if [ $? -eq 0 ]; then
              echo "Chrome workspace directory deleted successfully."
            else
              echo "Failed to delete Chrome workspace directory."
            fi
          else
            echo "Chrome workspace directory not found."
          fi

          if [ -d "$GITHUB_WORKSPACE/chromedriver" ]; then
            sudo chmod -R 777 "$GITHUB_WORKSPACE/chromedriver"
            sudo rm -rf "$GITHUB_WORKSPACE/chromedriver"
            if [ $? -eq 0 ]; then
              echo "ChromeDriver workspace directory deleted successfully."
            else
              echo "Failed to delete ChromeDriver workspace directory."
            fi
          else
            echo "ChromeDriver workspace directory not found."
          fi

          echo "Deleting version_info.txt..."
          if [ -f "$GITHUB_WORKSPACE/version_info.txt" ]; then
            sudo chmod 777 "$GITHUB_WORKSPACE/version_info.txt"
            sudo rm "$GITHUB_WORKSPACE/version_info.txt"
            if [ $? -eq 0 ]; then
              echo "version_info.txt deleted successfully."
            else
              echo "Failed to delete version_info.txt."
            fi
          else
            echo "version_info.txt not found."
          fi

          echo "Cleanup process completed."

      - name: Commit and push changes
        if: env.download_link != '' && env.CURRENT_VERSION != env.CURRENT_VERSION_EN
        run: |
          git config --global http.postBuffer 157286400
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Always touch a file to ensure the commit is registered
          touch update_timestamp.txt
          
          git add -A
          git stash
          git pull --rebase origin main || true
          git stash pop || true
          git add -A
          git commit -m "Updated ${{ env.CURRENT_VERSION }}"
          git push || git push --force