name: Update from dol-kr Release

on:
  schedule:
    - cron: '0 0 * * 0'  # 매주 일요일 자정에 실행
  workflow_dispatch:  # 수동으로 실행할 수 있도록 추가

jobs:
  update_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest release info
        id: get_release
        run: |
          latest_releases=$(curl -s https://api.github.com/repos/uotalkie/dol-kr/releases)
          echo "Latest releases response: ${latest_releases}"  # 디버깅을 위한 출력
          if echo "$latest_releases" | jq -e .message >/dev/null; then
            echo "Error: $(echo "$latest_releases" | jq -r .message)"
            exit 1
          fi
          latest_release=$(echo "$latest_releases" | jq -r '.[0]')
          asset_url=$(echo "$latest_release" | jq -r '.assets[] | select(.name | endswith(".7z")) | .browser_download_url')
          if [ -z "$asset_url" ]; then
            echo "Error: No .7z asset found in the latest release."
            exit 1
          fi
          echo "asset_url=${asset_url}" >> $GITHUB_ENV

      - name: Download latest release asset
        run: |
          curl -L -o release.7z "${{ env.asset_url }}"

      - name: Install 7zip
        run: sudo apt-get install p7zip-full -y

      - name: Unzip release files
        run: 7z x release.7z -oextracted_release

      - name: Move and rename HTML file to desired path
        run: |
          mv -f extracted_release/*.html DoL/DoLKr.html

      - name: Configure Git
        run: |
          git config --global user.name "StardropZone"
          git config --global user.email "toto941002@gmail.com"

      - name: Commit and push changes
        run: |
          cd ${{ github.workspace }}
          git add DoL/DoLKr.html
          git commit -m "Updated DoLKr.html from latest GitHub release"
          git push origin main
