name: Update HTML from GitLab

on:
  schedule:
    - cron: '0 0 * * 0'  # 매주 일요일 자정에 실행
  workflow_dispatch:  # 수동으로 실행할 수 있도록 추가

jobs:
  update_html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the latest pipeline ID
        id: get_pipeline
        run: |
          project_id=46941692  # 프로젝트 ID를 명시적으로 설정
          latest_pipeline=$(curl -s --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
              "https://gitlab.com/api/v4/projects/${project_id}/pipelines")
          echo "Latest pipeline response: ${latest_pipeline}"
          latest_pipeline_id=$(echo $latest_pipeline | jq -r '.[0].id')
          echo "latest_pipeline_id=${latest_pipeline_id}" >> $GITHUB_ENV

      - name: Validate latest pipeline ID
        run: |
          if [ "${{ env.latest_pipeline_id }}" == "null" ]; then
            echo "Error: Failed to fetch the latest pipeline ID."
            exit 1
          fi

      - name: Get the job ID for build:html
        id: get_job
        run: |
          job_id=$(curl -s --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
              "https://gitlab.com/api/v4/projects/${{ env.project_id }}/pipelines/${{ env.latest_pipeline_id }}/jobs" \
              | jq -r '.[] | select(.name=="build:html") | .id')
          echo "job_id=${job_id}" >> $GITHUB_ENV

      - name: Download artifacts from GitLab
        run: |
          curl --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
          -o build.zip \
          -L "https://gitlab.com/api/v4/projects/${{ env.project_id }}/jobs/${{ env.job_id }}/artifacts"

      - name: Unzip HTML files
        run: unzip build.zip -d extracted_html

      - name: Move HTML files to desired path
        run: mv extracted_html/* DoL/

      - name: Configure Git
        run: |
          git config --global user.name "StardropZone"
          git config --global user.email "toto941002@gmail.com"

      - name: Commit and push changes
        run: |
          cd ${{ github.workspace }}
          git add DoL/*
          git commit -m "Updated HTML files from the latest GitLab build:html artifacts"
          git push origin main
