name: Update HTML from GitLab

on:
  schedule:
    - cron: '0 0 * * 0'  # 매주 일요일 자정에 실행
  workflow_dispatch:  # 수동으로 실행할 수 있도록 추가

jobs:
  update_html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts from GitLab
        run: curl -o build.zip -L "https://gitlab.com/NullableSafety/dol-kr/-/jobs/artifacts/main/raw/build.zip?job=build:html"

      - name: Unzip HTML files
        run: unzip build.zip -d extracted_html

      - name: Move HTML files to desired path
        run: mv extracted_html/* path/to/github/repository/DoL/

      - name: Set up GitHub CLI
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token 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

      - name: Upload HTML files to GitHub
        run: |
          cd path/to/github/repository
          gh repo upload StardropZone/DolKr --branch main --clobber --file DoL/DoLKr.html
