name: GitHub Token

on:
  workflow_dispatch:  # 수동으로 실행할 수 있도록 추가

permissions:
  contents: write  # GITHUB_TOKEN에 쓰기 권한 부여

jobs:
  set_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # GITHUB_TOKEN 설정
      - name: Set GitHub Token environment variable
        run: echo "GITHUB_TOKEN=${{ secrets.G_TOKEN }}" >> $GITHUB_ENV

      # GIST_TOKEN 설정
      - name: Set Gist Token environment variable
        run: echo "GIST_TOKEN=${{ secrets.GIST_TOKEN }}" >> $GITHUB_ENV

      # GIST_ID 설정
      - name: Set Gist ID environment variable
        run: echo "GIST_ID=${{ secrets.GIST_ID }}" >> $GITHUB_ENV

      # 자바스크립트 실행
      - name: Run JavaScript script
        run: node script.js
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
