name: GitHub Token

on:
  schedule:
    - cron: '0 15 * * 6'  # 매주 토요일 UTC 15:00 (한국 시간 자정)
  workflow_dispatch:  # 수동으로 실행할 수 있도록 설정

permissions:
  contents: write  # GITHUB_TOKEN에 쓰기 권한 부여

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variable
        run: echo "GITHUB_TOKEN=${{ secrets.G_TOKEN }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 사용할 Python 버전 설정

      - name: Install dependencies
        run: pip install PyGithub  # PyGithub 설치

      - name: Run Python script
        run: python ./scripts/KrTransUpdate.py  # Python 스크립트 실행

      - name: Commit changes # 최신 태그로 커밋 메시지 작성
        run: |
          git add .
          git commit -m "${{ steps.run_script.outputs.LATEST_TAG }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}  # GitHub 토큰을 푸시 작업에 사용
