name: Update Kr Translation

on:
  schedule:
    - cron: '0 15 * * 6'  # 매주 토요일 UTC 15:00 (한국 시간 일요일 자정에 실행)
  workflow_dispatch:  # 수동 실행을 위한 옵션

jobs:
  update_files:
    runs-on: ubuntu-latest

    steps:
      # 현재 리포지토리 체크아웃
      - name: Checkout this repository
        uses: actions/checkout@v3

      # 최신 태그 정보 가져오기
      - name: Get latest tag from source repository
        id: get_latest_tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/uotalkie/dol-kr/tags | jq -r '.[0].name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      # 현재 리포지토리에서 scripts 폴더 내 KrVersionChecker.txt에 저장된 버전 가져오기
      - name: Get current version from this repository
        id: get_current_version
        run: |
          if [ -f scripts/KrVersionChecker.txt ]; then
            CURRENT_VERSION=$(cat scripts/KrVersionChecker.txt)
          else
            CURRENT_VERSION="none"
          fi
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      # 태그 비교 및 복사 여부 확인
      - name: Compare versions
        id: compare_versions
        run: |
          if [ "$LATEST_TAG" != "$CURRENT_VERSION" ]; then
            echo "New version found: $LATEST_TAG"
            echo "COPY_NEEDED=true" >> $GITHUB_ENV
          else
            echo "Already up to date"
            echo "COPY_NEEDED=false" >> $GITHUB_ENV
          fi

      # 변경된 파일들 추적 (현재 버전과 최신 버전 사이의 커밋 차이 확인)
      - name: Get list of changed files
        if: env.COPY_NEEDED == 'true'
        run: |
          CHANGED_FILES=$(curl -s https://api.github.com/repos/uotalkie/dol-kr/compare/$CURRENT_VERSION...$LATEST_TAG | jq -r '.files[].filename')
          echo "$CHANGED_FILES" > scripts/KrChangedFiles.txt
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # 변경된 파일을 복사 (경로 유지 및 덮어쓰기)
      - name: Copy changed files from source repository
        if: env.COPY_NEEDED == 'true'
        run: |
          mkdir -p KrTrans
          while IFS= read -r file; do
            dir=$(dirname "./KrTrans/$file")
            mkdir -p "$dir"
            curl -L -o "./KrTrans/$file" "https://raw.githubusercontent.com/uotalkie/dol-kr/main/$file"
          done <<< "$CHANGED_FILES"

      # 최신 태그를 scripts 폴더 내 KrVersionChecker.txt에 기록
      - name: Update version in scripts/KrVersionChecker.txt
        if: env.COPY_NEEDED == 'true'
        run: |
          echo "$LATEST_TAG" > scripts/KrVersionChecker.txt

      # 변경된 파일들 커밋 및 푸시
      - name: Commit and push changes
        if: env.COPY_NEEDED == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "$LATEST_TAG" || echo "Nothing to commit"
          git push