name: Update Kr Translation

on:
  schedule:
    - cron: '0 15 * * 6'  # 매주 토요일 UTC 15:00 (한국 시간 일요일 자정에 실행)
  workflow_dispatch:  # 수동 실행을 위한 옵션

jobs:
  update_files:
    runs-on: ubuntu-latest

    steps:
      # 현재 리포지토리 체크아웃
      - name: Checkout this repository
        uses: actions/checkout@v3

      # GITHUB_TOKEN 설정
      - name: Set GitHub Token environment variable
        run: echo "GITHUB_TOKEN=${{ secrets.G_TOKEN }}" >> $GITHUB_ENV

      # 최신 태그 정보 가져오기
      - name: Get latest tag from source repository
        id: get_latest_tag
        run: |
          LATEST_TAG=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/uotalkie/dol-kr/tags | jq -r '.[0].name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      # 현재 리포지토리에서 scripts 폴더 내 KrVersionChecker.txt에 저장된 버전 가져오기
      - name: Get current version from this repository
        id: get_current_version
        run: |
          if [ -f scripts/KrVersionChecker.txt ]; then
            CURRENT_VERSION=$(cat scripts/KrVersionChecker.txt)
          else
            CURRENT_VERSION="none"
          fi
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      # 태그 비교
      - name: Compare versions
        id: compare_versions
        run: |
          if [ "$LATEST_TAG" != "$CURRENT_VERSION" ]; then
            echo "New version found: $LATEST_TAG"
            echo "COPY_NEEDED=true" >> $GITHUB_ENV
          else
            echo "Already up to date"
            echo "COPY_NEEDED=false" >> $GITHUB_ENV
          fi

      # KrTrans 폴더 내의 기존 파일 삭제
      - name: Remove existing files in KrTrans
        if: env.COPY_NEEDED == 'true'
        run: |
          rm -rf KrTrans/*

      # 최신 태그의 소스 리포지토리에서 KrTrans 폴더로 모든 파일 복사
      - name: Copy all files from source repository to KrTrans
        if: env.COPY_NEEDED == 'true'
        run: |
          # 임시 디렉토리 생성 및 소스 리포지토리 클론
          mkdir temp_repo
          git clone --depth 1 --branch $LATEST_TAG https://$GITHUB_TOKEN@github.com/uotalkie/dol-kr.git temp_repo
          
          # KrTrans 폴더로 파일 복사
          cp -r temp_repo/* KrTrans/
          
          # 임시 디렉토리 제거
          rm -rf temp_repo

      # 파일 인코딩 확인 및 변환 (UTF-8로 인코딩되지 않은 경우 변환)
      - name: Check and convert file encoding to UTF-8
        if: env.COPY_NEEDED == 'true'
        run: |
          for file in KrTrans/*; do
            if [ -f "$file" ]; then
              ENCODING=$(file -bi "$file" | awk -F "=" '{print $2}')
              if [ "$ENCODING" != "utf-8" ]; then
                echo "Converting $file from $ENCODING to utf-8"
                TEMP_FILE="${file}.tmp"
                iconv -f $ENCODING -t UTF-8 "$file" -o "$TEMP_FILE" && mv "$TEMP_FILE" "$file" || echo "Failed to convert $file"
              fi
            fi
          done

      # 최신 태그를 scripts 폴더 내 KrVersionChecker.txt에 기록
      - name: Update version in scripts/KrVersionChecker.txt
        if: env.COPY_NEEDED == 'true'
        run: |
          echo "$LATEST_TAG" > scripts/KrVersionChecker.txt

      # 변경된 파일들 커밋 및 푸시
      - name: Commit and push changes
        if: env.COPY_NEEDED == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "$LATEST_TAG" || echo "Nothing to commit"
          git push
